#!/bin/bash

set -e

first=$1
rest=${*:2}

function play() {
  ansible-playbook $rest -i inventory/$1 --sudo playbooks/site.yml
}

test -f inventory/$1 || echo "Usage $0 (vagrant|testing|production) [options]"
test -f inventory/$1 || exit 1

play $1
